import React from 'react'
import styles from './style.module.css'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: "About App",
  description: "Generated by create next app",
};


export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

    
    return (
    <div>
      About Navbar
      <main className={styles.main}>
        {children}
      </main>
    </div>
  )
}
